name: Auto-Green

permissions:
  pull-requests: write
  contents: write
  repository-projects: write

on:
  workflow_dispatch:
    inputs:
      log:
        description: "Commit Log"
        required: true
        default: "a commit a day keeps your girlfriend away"
  schedule:
    - cron: "25 9 * * 1-6"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Pull
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@gmail.com"
          git remote set-url origin https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
      - name: Init NPM
        run: |
          npm install
          echo "$(node index.js)" >> autogreen.txt
          echo "modify at $(date)" >> autogreen.txt
          git add autogreen.txt

      - name: Commit (default)
        if: github.event.inputs.log == 0
        run: git commit --allow-empty -m "$(node index.js)"

      - name: Commit (input)
        if: github.event.inputs.log != 0
        run: git commit --allow-empty -m "${{ github.event.inputs.log }}"

      - name: Push
        run: |
          git push
